CREATE DATABASE IF NOT EXISTS mydatabase;

USE mydatabse;

CREATE TABLE IF NOT EXISTS USER(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(25) NOT NULL,
    GENDER VARCHAR(15) NOT NULL,
    AGE VARCHAR(25) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PRIMARY KEY(ID)
    )

CREATE TABLE IF NOT EXISTS ORDER(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    userID INT(11) NOT NULL,
    price INT(11) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY(userID) REFERENCES USER(ID)
)

