CREATE DATABASE IF NOT EXISTS mydatabase;

USE mydatabase;

CREATE TABLE IF NOT EXISTS users(
    id INT(11) NOT NULL AUTO_INCREMENT,
    userName VARCHAR(25) NOT NULL,
    gender VARCHAR(15) NOT NULL,
    age VARCHAR(25) NOT NULL,
    email VARCHAR(50) NOT NULL,
    PRIMARY KEY(id)
    );

CREATE TABLE IF NOT EXISTS orders(
    id INT(11) NOT NULL AUTO_INCREMENT,
    userID INT(11) NOT NULL,
    price INT(11) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(userID) REFERENCES users(id) ON DELETE CASCADE
);

